Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,89 +1,112 @@
-# Java Maven CircleCI 2.0 configuration file
-#
-# Check https://circleci.com/docs/2.0/language-java/ for more details
-#
 version: 2.1
-#orbs:
- # pr-comment: benjlevesque/pr-comment@0.1.4
+
+references:
+  workspace_root: &workspace_root
+    /tmp/workspace
+  attach_workspace: &attach_workspace
+    attach_workspace:
+      at: *workspace_root
+
 jobs:
-  build:
-    docker:
-      # specify the version you desire here
-      - image: circleci/openjdk:8-jdk
-      
-      # Specify service dependencies here if necessary
-      # CircleCI maintains a library of pre-built images
-      # documented at https://circleci.com/docs/2.0/circleci-images/
-      # - image: circleci/postgres:9.4
+    build:
+        docker:
+            - image: circleci/openjdk:8-jdk-node
+        working_directory: ~/repo
+        environment:
+            MAVEN_OPTS: -Xmx3200m
+            
+        steps:
+            - *attach_workspace
+            - checkout
+            - restore_cache:
+                keys:
+                    - v1-dependencies-{{ checksum "pom.xml" }}
+                    # fallback to using the latest cache if no exact match is found
+                    - v1-dependencies-
+            
+            - run: mvn dependency:go-offline
+            - save_cache:
+                paths:
+                    - ~/.m2
+                key: v1-dependencies-{{ checksum "pom.xml" }}
+                
+            # build the apps!!
+            - run:
+                name: Build the application
+                command: |
+                    mvn clean package
+                    mkdir -p /tmp/workspace/target
+                    mv target/hello-shiftleft-0.0.1.jar /tmp/workspace/target/
+                    cp uat.sh /tmp/workspace/target
+                    
+            - persist_to_workspace:
+                root: *workspace_root
+                paths:
+                    - target
 
-    working_directory: ~/repo
-
-    environment:
-      # Customize the JVM maximum heap limit
-      MAVEN_OPTS: -Xmx3200m
-    
-    steps:
-      - checkout
-      # Install SL agent
-      - run: 
-          name: Install Shiftleft agent
-          command: curl https://www.shiftleft.io/download/sl-latest-linux-x64.tar.gz > /tmp/sl.tar.gz && sudo tar -C /usr/local/bin -xzf /tmp/sl.tar.gz
-                 
-      # Download and cache dependencies
-      - restore_cache:
-          keys:
-          - v1-dependencies-{{ checksum "pom.xml" }}
-          # fallback to using the latest cache if no exact match is found
-          - v1-dependencies-
-
-      - run: mvn dependency:go-offline
-
-      - save_cache:
-          paths:
-            - ~/.m2
-          key: v1-dependencies-{{ checksum "pom.xml" }}
-          
-     # build the apps!!
-      - run: 
-          name: Build the application
-          command: mvn clean package
-     
-      - run:
-          name: Update PATH and Define Environment Variable at Runtime
-          command: |
-            echo 'export APP_NAME=HelloShiftLeft-Java--CircleCI' >> $BASH_ENV
-            source $BASH_ENV
-      
-     # Analyze for security
-      - run: 
-          name: Analyze for security bugs
-          command: sl analyze --wait --version-id $CIRCLE_BUILD_NUM  --tag branch=$CIRCLE_BRANCH --app $APP_NAME target/hello-shiftleft-0.0.1.jar
-          
-     #  Prioritize security bugs
-     #  [Run user acceptance smoke tests related to security]
-      - run: 
-          name: Prioritize security bugs
-          command: sh uat.sh
-          
-     #  Test Security Results
-      - run: 
-          name: Assert build quality against security standards
-          command: |
-            BUILD_RESULT=$(curl --fail --show-error -X GET "https://www.shiftleft.io/api/v3/public/org/$SHIFTLEFT_ORG_ID/app/$APP_NAME/tag/branch/$CIRCLE_BRANCH/build" -H 'Accept: */*' -H "Authorization: Bearer $SHIFTLEFT_API_TOKEN" -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Host: www.shiftleft.io' -H 'accept-encoding: text/plain, deflate' -H 'cache-control: no-cache' -H 'cookie: Cookie_3=value' -s -b Cookie_3=value)
-            echo $BUILD_RESULT
-            SUCCESS=$(echo $BUILD_RESULT | grep "success")
-            if [ -z "$SUCCESS" ]; then
-                echo Filter triggered: Todo: add code for pr-comment and exit 1                
-                exit 0
-            fi
-            exit 0
-    
-     #  Comment on Pull Request if build fails due to security issues
-      - run:
-          name: Add comments to GitHub Pull Request
-          command: echo $BUILD_RESULT
-          when: on_fail
-          
-     #  Comment on Pull Request if build fails due to security issues
-     # - pr-comment:
-     #     comment: "Build result - $BUILD_RESULT"
+                
+    ShiftLeft_code_analysis:
+        docker:
+            - image: circleci/openjdk:8-jdk-node
+        working_directory: ~/repo
+        
+        steps:
+            - attach_workspace:
+                at: .
+            - run:
+                name: Update PATH and Define Environment Variable at Runtime
+                command: |
+                    echo 'export APP_NAME=Docker_Demo_App' >> $BASH_ENV
+                    source $BASH_ENV
+            
+            - run:
+                name: Install ShiftLeft agent
+                command: curl https://www.shiftleft.io/download/sl-latest-linux-x64.tar.gz > /tmp/sl.tar.gz && sudo tar -C /usr/local/bin -xzf /tmp/sl.tar.gz
+                
+            - run:
+                name: Analyze for security bugs
+                command: sl analyze --wait --tag branch=$CIRCLE_BRANCH --app $APP_NAME target/hello-shiftleft-0.0.1.jar
+                
+            #   Prioritize security bugs
+            - run:
+                name: Prioritize security bugs
+                command: sh target/uat.sh
+                
+            #   Test Security Results
+            - run:
+                name: Assert build quality against security standards
+                command: |
+                    BUILD_RESULT=$(curl -X GET "https://www.shiftleft.io/api/v3/public/org/$SHIFTLEFT_ORG_ID/app/$APP_NAME/tag/branch/$CIRCLE_BRANCH/build" -H "Authorization: Bearer $SHIFTLEFT_API_TOKEN" -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Host: www.shiftleft.io' -H 'accept-encoding: text/plain, deflate' -H 'cookie: Cookie_3=value' -s -b Cookie_3=value)
+                    if [ $(echo $BUILD_RESULT | grep "success") ]; then
+                        PR_COMMENT="ShiftLeft did not detect any vulnerabilities that violate policy. This PR can be merged."
+                    else
+                        URL="https://shiftleft.io/"
+                        URL+=$(echo $BUILD_RESULT | jq -r '.errorDetails')
+                        PR_COMMENT="ShiftLeft found vulnerabilities that violate policy. Go here for more details - $URL"
+                    fi
+                    if [ ! -z "$CIRCLE_PULL_REQUEST" ]; then
+                        PR_USER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/' -f4)
+                        PR_REPO=$(echo $CIRCLE_PULL_REQUEST | cut -d '/' -f5)
+                        PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/' -f7)
+                        curl -H "Authorization: token $GH_AUTH_TOKEN" -X POST -d "{\"body\": \"$PR_COMMENT\"}" https://api.github.com/repos/$PR_USER/$PR_REPO/issues/$PR_NUMBER/comments
+                        if [ ! $(echo $BUILD_RESULT | grep "success") ]; then
+                            echo "Failing the build since PR violates security policy"
+                            exit 1
+                        fi
+                    else
+                        echo "No PR information. Was this a commit/merge to the master branch?"
+                         if [ ! $(echo $BUILD_RESULT | grep "success") ]; then
+                            echo "Failing the build since commit/merge violates security policy"
+                            exit 1
+                        fi
+                    fi
+                    
+workflows:
+    version: 2
+    build_and_test:
+        jobs:
+            - build
+#            - ShiftLeft_code_analysis
+            - ShiftLeft_code_analysis:
+                requires:
+                    - build
